WorkoutBuddy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('find',views.find,name='find'),
    path('about',views.about,name='about'),
    path('excercise_guide',views.excercise_guide,name='excercise_guide'),
    path('accounts/',include('uniauth.urls.cas_only', namespace='uniauth')),
    path('database/',include('buddyrequest.urls')),
    path('partners/',include('buddyrequest.urls')),
    path('contacts/',views.contacts,name='contacts')
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('login', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout, name='logout')
]

WorkoutBuddy/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

import csv

def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

def contacts(request):
    return render(request,'contact.html')

@login_required(login_url='/accounts/login')
def find(request):
    return render(request,'find.html')


def excercise_guide(request):
    return render(request,'excercise_guide.html')

WorkoutBuddy/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<head>

  <title>TigerGainz - About/FAQs</title>

  <!--Page Stylesheet-->
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/About-FAQStyle.css' %}" />

</head>

<body>

  <div class="headerpic"><img src="https://cdn.discordapp.com/attachments/735319507341672642/737054815393153114/FAQ_2.jpg" class="img.responsive" style="width:55%">
  </div>

  <!--About TigerGainz, Featuring the FAQs-->

  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  </body>

  <div class="border-black">
    <h1 class="display-5"><strong>About TigerGainz</strong></h1>
  </div>
  <br />
  <br />

  <div class="jumbotron">
    <div class="border-white">
      <p class="lead">Why Was TigerGainz Created?</p>
      <hr class="my-4">
      <div class="border-orange">
        <div class="jumbotron white-background">
          <p>Despite the COVID-19 pandemic and virtual classes, Vinay Konuru ’24 and Ben Cai ’24 still wanted
            to work out
            with friends. Unfortunately, everyone had different schedules, goals, and exercise preferences,
            especially in quarantine. As a result, Vinay and Ben had to exercise on their own, and they
            struggled to
            motivate themselves. Fortunately, Vinay and Ben met each other and other workout-eager
            classmates in the
            Class of 2024 Princeton group chat. After much planning, they finally found suitable workout
            partners.
          </p>
        </div>
      </div>
      <hr class="my-4">

      <div class="media p-3">
        <img src="https://cdn.discordapp.com/attachments/735319507341672642/736276124518318160/Side_Icon_Left.png" class="align-self-center mr-3 tiger-icons">
        <div class="media-body list what-if">
          <strong><i>But what if this process of finding workout buddies
              or groups with the most
              fitting workout partners was not only faster but more accessible?
            </i></strong>
        </div>
        <img src="https://cdn.discordapp.com/attachments/735319507341672642/736276156071936062/Side_Icon_Right.png" class="align-self-center mr-3 tiger-icons">
      </div>
      <hr class="my-4">
      <div class="border-orange">
        <div class="jumbotron white-background">
          <p>That’s why Vinay, Ben, Eugene Liu ’24 and Elizabeth Medina ’24 co-founded TigerGainz in the hopes
            of creating a closer community on- and off-campus.
          </p>
          <p>If you have any questions or concerns, please view our FAQ or visit the <a class="links" href="{% url 'contacts' %}">“Contact Us”</a> section to email one
            of the co-founders or complete our feedback form.
          </p>
          <p>Happy Exercising!</p>
        </div>
      </div>
      <hr class="my-4">
      <div class="lead">
        <p>With much love,
        </p>
        <div class="much-love">
          <p>The TigerGainz Gang: Ben, Vinay, Eugene, & Elizabeth</p>
        </div>
      </div>
    </div>
  </div>

  <div class="border-black">
    <h1 class="display-5"><strong>FAQs</strong></h1>
  </div>
  <br />
  <br />

  <div class="jumbotron">
    <div class="border-white">
      <p class="lead"><strong>Below are answers to FAQs. If you still have questions or concerns, <a class="links-white" href="{% url 'contacts' %}">please email
            one of the co-founders or complete our feedback form.</a></strong></p>
      <hr class="my-4">
      <div class="border-orange">
        <div class="jumbotron white-background">

          <div class="container">
            <article class="panel-group bs-accordion" id="accordion" role="tablist" aria-multiselectable="true">
              <section class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title">
                    <a class="links" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      Click to See FAQs
                      <span class="glyphicon glyphicon-chevron-right pull-right" aria-hidden="true"></span>
                    </a>
                  </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  </br>
                  <hr class="my-4">
                  <div class="panel-body">
                    <h3 class="links">1. Who has access to
                      my TigerGainz responses/workout preferences? What is my data used for?</h3>
                    <hr class="my-4">
                    <p>All your TigerGainz responses/workout preferences are
                      securely
                      stored and solely used to create workout buddy matches and your TigerGainz
                      profile. Your
                      TigerGainz profile is only available to other TigerGainz users who have still
                      not chosen
                      a match.</p>
                    <hr class="my-4">
                    <h3 class="links">2. My
                      current
                      Princeton workout buddy/group and I decided that we are not the best fit for
                      each
                      other. Can we request new Princeton workout buddies/groups? If so, how?</h3>
                    <hr class="my-4">
                    <p>Yes, you both can request new Princeton workout
                      buddies/groups. To
                      do this, please go to the Database section and click the “Take me off the
                      database
                      please” button. Then, click the sign up button to complete the form again (note:
                      this
                      will replace your old responses).</p>
                    <hr class="my-4">
                    <h3 class="links">3.
                      Can I edit my
                      workout preferences? If so, how?</h3>
                    <hr class="my-4">
                    <p>Yes, you can edit your workout preferences. To do this,
                      please go to
                      the Database section and click the “Take me off the database please” button.
                      Then, click
                      the sign up button to complete the form again (note: this will replace your old
                      responses). However, this also means you may get different matches.</p>
                    <hr class="my-4">
                    <h3 class="links">4. Why am I getting no matches on my initial search? What
                      should I do? How long will I have to wait for a match?</h3>
                    <hr class="my-4">
                    <p>In the unlikely scenario that TigerGainz finds no suitable
                      matches upon form submission - most likely due to uncommon workout preferences -
                      you should click the “Take me off the database please” button in the Database
                      section and then complete form again with broader preferences. On the other
                      hand, if you have already submitted the form and are still not
                      getting matches, that means someone hasn’t chosen you to be their workout buddy
                      or group yet. You may have to wait a few days. If you don’t want to wait for
                      someone to choose you, please resubmit your form
                      (see above) or check out the TigerGainz directory.</p>
                    <hr class="my-4">
                    <h3 class="links">5. I haven’t heard back from TigerGainz in a while and I’m
                      still looking for a match. What should I do?</h3>
                    <hr class="my-4">
                    <p>Please go to the Database section and click the “Take me
                      off the database please” button. Then, click the sign up button to complete the
                      form again. Hopefully, if there are still Princetonians looking for a workout
                      buddy or
                      group, you should instantly get matches. Alternatively, you can check out the
                      TigerGainz directory.</p>
                    <hr class="my-4">
                    <h3 class="links">6. How can I maximize my chances of getting a match?</h3>
                    <hr class="my-4">
                    <p>To maximize your chances of getting a match, you should
                      select as many workout preferences you are comfortable with and choose the
                      “average” or “most common” response.</p>
                    <hr class="my-4">
                    <h3 class="links">7. Am I able to view other people’s profiles even if I
                      haven’t matched with them?</h3>
                    <hr class="my-4">
                    <p>Yes, you can view other people’s profiles in the directory
                      even if they aren’t a match but only if you signed up for TigerGainz and you
                      have not already found a match.</p>
                  </div>
                </div>
              </section>
            </article>
          </div>

        </div>

      </div>
    </div>
  </div>
</body>

{% endblock %}

WorkoutBuddy/templates/base.html
<html lang="en">

<head>
  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- Bootstrap core CSS -->
  <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!--Font Used: Noto Sans from Google Fonts-->
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">

  <!--Base Stylesheet-->
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/BaseStyle.css' %}" />

  <!--Logo-->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_package_v0/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_package_v0/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_package_v0/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'favicon_package_v0/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'favicon_package_v0/safari-pinned-tab.svg' %}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

</head>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
  $(document).ready(function() {
    $("#myModal").modal('show');
  });
</script>

<!--added for the navbar-->

<script>
  $(document).ready(function() {
    $('.navbar-dark > button').on('click', function() {
      $('.navbar-dark').toggleClass('color-changed');
    });
  });
</script>


<script>
  function myFunction() {
    document.getElementById("navbar-light").style.backgroundColor = "white";
  }
</script>

<body>

  <!--Header -->
  <nav class="navbar fixed-top navbar-dark bg-light navbar-custom">
    <a class="navbar-brand" href="{% url 'home' %}"><img src="https://cdn.discordapp.com/attachments/735319507341672642/736046532834492456/IMG_0037.PNG" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">TigerGainz</a>
    <!-- <span class="navbar-text ml-auto">
      Your Current Partner is:
    </span> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon custom-toggler"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link dropdown-item" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link dropdown-item" href="{% url 'excercise_guide' %}">Excercise Guide</a>
        </li>
        <li class="nav-item active">
          {% if user.is_authenticated %}
            {% load base_tags %}
            {% if user|check_requests %}
              <a class="nav-link dropdown-item" href="{% url 'profile' user.id %}">My Request Details</a>
              {% if user|check_partner %}
                <a class="nav-link" href="{% url 'partner' %}">Partner</a>
              {% else %}
                <a class="nav-link dropdown-item" href="{% url 'database' %}">Waiting List</a>
              {% endif %}
            {% endif %}
          {% else %}
            <a class="nav-item nav-link dropdown-item" href="{% url 'uniauth:login' %}">Log In</a>
          {% endif %}
        </li>
        <li class="nav-item active">
          <a class="nav-link dropdown-item" href="{% url 'about' %}">About & FAQ</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link dropdown-item" href="{% url 'contacts' %}">Contact Us :)</a>
        </li>
      </ul>
    </div>
  </nav>
</body>
{% block content %}

{% endblock %}
<!-- <footer class="footer">
    <div class="container text-center">
        ©AwesomeSauce {% now "Y" %}
    </div>
</footer> -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</html>

WorkoutBuddy/templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<head>

  <title>TigerGainz - Feedback & Contact Us</title>

  <!--Page Stylesheet-->
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/ContactUsStyle.css' %}" />

</head>

<body>

  <div class="headerpic"><img src="https://cdn.discordapp.com/attachments/735319507341672642/737053520678748221/Contact_Us_2.jpg" class="align-self-center" style="width:65%">
  </div>

  <!--Contacts and Bios-->

  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  </body>

  <div class="border-black">
    <h1 class="display-5"><strong>Contact Us</strong></h1>
  </div>
  <br />
  <br />

  <div class="jumbotron">
    <div class="border-white">
      <h2 class="lead"><strong>Feedback</strong></h2>
      <hr class="my-4">
      <div class="border-orange">
        <div class="jumbotron white-background">
          <p>Have feedback for us? Fill out <a class="links" href="https://docs.google.com/forms/d/e/1FAIpQLScHBTfxXng_85fVKSKnOI5Wxhd0264pw4JYl1HNODwdKW6VFg/viewform?usp=pp_url">this</a>
            form!</p>
          <p>For general questions, please refer to the FAQs located on the <a class="links" href="{% url 'about' %}">"About & FAQ"</a>
            page. Any additional
            questions, comments, or concerns can be directed to one of the founders linked below.</p>
        </div>
      </div>
    </div>
  </div>


  <div class="border-black">
    <h1 class="display-5"><strong>Management</strong></h1>
  </div>
  <br />
  <br />

  <div class="jumbotron">
    <div class="border-white">
      <h2 class="lead"><strong>Get to know us!</strong></h2>
      <hr class="my-4">
      <div class=" border-orange">
        <div class="jumbotron white-background">

          <div class="row">
            <div class="column">
              <div class="pic-container">
                <img class="img-fluid bio-pic" src="https://cdn.discordapp.com/attachments/735319507341672642/765581581548388362/Unknown.jpeg">
                <div class="overlay">
                  <div class="text"> Email: vkonuru@princeton.edu <br/> <br/>Hey! My name is Vinay, and I am one of the co-founders. I am a full stack developer
                    for this project, with a priority on the middle layer and backend. I focused on building the
                    website, co-developing the matching algorithm, and managing the database. I’ve been really
                    excited to bring TigerGainz to the Princeton community since we began working on this project,
                    because I know it has the potential to help tigers across the globe live healthier, happier
                    lives regardless of where we are.</div>
                </div>
              </div>
              <hr class="my-4">
              <p class="lead">Vinay Konuru</p>
              <hr class="my-4">
              <a href="mailto:vkonuru@princeton.edu" class="btn btn-lg btn-secondary">Contact Me <br />
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                </svg></a>
            </div>

            <div class="column">
              <div class="pic-container">
                <img class="img-fluid bio-pic" src="https://cdn.discordapp.com/attachments/735319507341672642/737028647080427540/Screen_Shot_2020-07-26_at_3.28.28_PM.png">
                <div class="overlay">
                  <div class="text">Email: el25@princeton.edu <br/> <br/>Hi! My name is Eugene (℅ 2024), and I am interested in Computer Science—specifically
                    artificial intelligence and machine learning. I am one of the co-founders and I was responsible
                    for building the matching algorithm and email automation. Building this web app has been
                    extremely rewarding, and I hope you all find some utility out of it!</div>
                </div>
              </div>
              <hr class="my-4">
              <p class="lead">Eugene Liu</p>
              <hr class="my-4">
              <a href="mailto:el25@princeton.edu" class="btn btn-lg btn-secondary">Contact Me <br />
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                </svg></a>
            </div>

            <div class="column">
              <div class="pic-container">
                <img class="img-fluid bio-pic" src="https://cdn.discordapp.com/attachments/735319507341672642/735927771649409114/PrincetonID.jpg">
                <div class="overlay">
                  <div class="text">Email: pemedina@princeton.edu <br/> <br/>Elizabeth here! A member of the Class of 2024, I’m interested in Computer Science (quantum computing in particular) as well as other
                    creative pursuits (ranging from digital art to music). I am one of the co-founders of TigerGainz and am
                    the primary front-end developer of the website.</div>
                </div>
              </div>
              <hr class="my-4">
              <p class="lead">Elizabeth Medina</p>
              <hr class="my-4">
              <a href="mailto:pemedina@princeton.edu" class="btn btn-lg btn-secondary">Contact Me <br />
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                </svg></a>
            </div>

            <div class="column">
              <div class="pic-container">
                <img class="img-fluid bio-pic" src="https://media.discordapp.net/attachments/735319507341672642/735951335085572116/BenCaiPhoto.png">
                <div class="overlay">
                  <div class="text">Email: bccai@princeton.edu <br/> <br/>Hi! I’m Ben, a Freshman (Class of 2024) from Rhode Island interested in economics. I
                    am one of the co-founders and I am responsible for the website’s content. Having desired
                    something like TigerGainz myself, I hope you enjoy it! Happy exercising!</div>
                </div>
              </div>
              <hr class="my-4">
              <p class="lead">Ben Cai</p>
              <hr class="my-4">
              <a href="mailto:bccai@princeton.edu" class="btn btn-lg btn-secondary">
                Contact Me <br />
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                </svg>
              </a>
            </div>

          </div>
        </div>
      </div>
    </div>
</body>

{% endblock %}